[package]
authors = ["alisa <alisa.dammer@gmail.com>"]
edition = "2018"
name = "trackme"
version = "0.1.0"
[dependencies]
chrono = "~0.4.19"
clap = "*"
structopt = "~0.3"
strum = "0.19"
strum_macros = "0.19"
csv = "~1.1"
