/// Mental state tracking form
/// ---
///
/// Currently implemented fields are primary classes of emotions or so called "primary emotions".
/// These emotions are normally very strong and obvious, additionally since there are so many
/// secondary and tertiary emotions a list with free input is available.
/// It is planned to add the list of secondary emotions to the project as a orientation entity.
/// Parrot's emotions tree structure: [wiki](!https://en.wikipedia.org/wiki/Emotion_classification) 
///
use chrono::{DateTime, Utc};
use std::collections::HashMap;

#[derive(Debug, Clone)]
pub enum PrimaryEmotionsEnum {
    anger,
    sadness,
    fear,
    joy,
    surprise,
    love
}

#[derive(Debug, Clone)]
pub enum SecondaryAndTertiaryEmotions {
    Affection,
    Lust,
    Longing,
    Cheerfulness,
    Zest,
    Contenment,
    Pride,
    Optimism,
    Enthrallment,
    Relief,
    Surprise,
    Irritability,
    Exasperation,
    Rage,
    Disgust,
    Envy,
    Torment,
    Suffering,
    Sadness,
    Dissapointment,
    Shame,
    Neglect,
    Sympathy,
    Horror,
    Nervousness,
    // here start tertiary
    Adoration,
    Fondness,
    Liking,
    Attraction,
    Caring,
    Tenderness,
    Compassion,
    Sentimentality,
    Desire, 
    Passion, 
    Inatuation,
    Amusement,
    Bliss,
    Gaiety,
    Glee,
    Jolliness,
    Joviality,
    Delight,
    Enjoyment,
    Gladness,
    Happiness,
    Jubiliation,
    Elation,
    Satisfaction, 
    Ecstasy,
    Euphoria,
    Enthusiasm,
    Zeal, 
    Excitement,
    Thrill,
    Exhallaration,
    Pleasure,
    Triumph,
    Eagerness,
    Hope,
    Rapture,
    Amazement,
    Astonishment,
    Aggravation,
    Agitation,
    Annoyance,
    Grouchy,
    Grumpy,
    Crosspatch,
    Frustration,
    Outrage,
    Fury,
    Wrath,
    Hostility,
    Ferocity,
    Bitterness,
    Hatred,
    Scorn,
    Spite,
    Vengefulness,
    Dislike,
    Resentment,
    Jealousy,
    Agony, 
    Anguish,
    Hurt,
    Depression, 
    Despair,
    Gloom, 
    Glumness,
    Unhappiness,
    Grief,
    Sorrow,
    Woe,
    Misery,
    Melancholy,
    Dismay, 
    Displeasure,
    Guilt,
    Regret,
    Remorse,
    Alienation,
    Defeatism,
    Dejection,
    Embarrassment,
    Homesickness,
    Humiliation,
    Insecurity,
    Insult,
    Isolation,
    Loneliness,
    Rejection,
    Pity,
    Alarm,
    Shock,
    Fright,
    Terror,
    Panic,
    Hysteria,
    Mortification,
    Anxiety,
    Suspense,
    Uneasiness,
    Apprehension,
    Worry,
    Distress,
    Dread
}

pub struct Emotions {
    pub timestamp: DateTime<Utc>,
    pub primary: HashMap<PrimaryEmotionsEnum, i16>,
    pub secondary: HashMap<SecondaryAndTertiaryEmotions, i16>,  // Name of the emotions outside of primary emotions 
    pub comment: Option<String>
}

